;;; pb/xp/windows.el -*- lexical-binding: t; -*-


(defhydra hydra-window (:color pink :columns 4)
  "Window Management"
  ("h" evil-window-left "move left")
  ("j" evil-window-down "move down")
  ("k" evil-window-up "move up")
  ("l" evil-window-right "move right")
  ("H" (lambda ()
         (interactive)
         (evil-window-move-far-left)
         (evil-window-left))
   "move to leftmost")
  ("J" (lambda ()
         (interactive)
         (evil-window-move-very-bottom)
         (evil-window-down))
   "move to bottommost")
  ("K" (lambda ()
         (interactive)
         (evil-window-move-very-top)
         (evil-window-up))
   "move to topmost")
  ("L" (lambda ()
         (interactive)
         (evil-window-move-far-right)
         (evil-window-right))
   "move to rightmost")
  ("-" split-window-below "split vertically")
  ("/" split-window-right "split horizontally")
  ("=" balance-windows "balance")
  ("d" delete-window "delete")
  ("s" (lambda ()
         (interactive)
         (evil-window-split)
         (evil-window-down 1))
   "split and move down")
  ("v" (lambda ()
         (interactive)
         (evil-window-vsplit)
         (evil-window-right 1))
   "split and move right")
  ;("t" nil "transpose")
  ("o" delete-other-windows "delete others")
  ("w" ace-swap-window "swap")
  ("q" nil "quit" :exit t)
  ("<escape>" nil "quit" :exit t))


(setq aw-keys '(?1 ?2 ?3 ?4 ?5 ?6 ?7 ?8 ?9 ?0))

(map! "s-w" 'hydra-window/body)
